[build]
  publish = "."

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/patterns"
  to = "/.netlify/functions/patterns"
  status = 200
  force = true

[[redirects]]
  from = "/api/logs"
  to = "/.netlify/functions/patterns"
  status = 200
  force = true

